# Generated by Django 5.0.6 on 2026-03-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=191, unique=True)),
                ('password_hash', models.CharField(db_column='passwordHash', max_length=191)),
                ('role', models.CharField(default='ADMIN', max_length=191)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'AdminUser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField(db_column='appointmentDate')),
                ('slot', models.CharField(choices=[('MORNING', 'MORNING'), ('EVENING', 'EVENING')], max_length=20)),
                ('patient_name', models.CharField(db_column='patientName', max_length=191)),
                ('patient_age', models.IntegerField(db_column='patientAge')),
                ('patient_phone', models.CharField(db_column='patientPhone', max_length=191)),
                ('status', models.CharField(choices=[('BOOKED', 'BOOKED'), ('WAITING', 'WAITING'), ('CALLED', 'CALLED'), ('DONE', 'DONE'), ('NO_SHOW', 'NO_SHOW')], default='BOOKED', max_length=20)),
                ('arrived_at', models.DateTimeField(blank=True, db_column='arrivedAt', null=True)),
                ('doctor_queue_number', models.IntegerField(blank=True, db_column='doctorQueueNumber', null=True)),
                ('daily_queue_number', models.IntegerField(blank=True, db_column='dailyQueueNumber', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'Appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicVideo',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=191)),
                ('filename', models.CharField(max_length=191)),
                ('mime_type', models.CharField(db_column='mimeType', max_length=191)),
                ('size_bytes', models.IntegerField(db_column='sizeBytes')),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(db_column='sortOrder', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'ClinicVideo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyQueueCounter',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField(db_column='appointmentDate', unique=True)),
                ('last_number', models.IntegerField(db_column='lastNumber', default=0)),
            ],
            options={
                'db_table': 'DailyQueueCounter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisplayState',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('IDLE', 'IDLE'), ('CALLING', 'CALLING'), ('OFF', 'OFF')], default='IDLE', max_length=20)),
                ('appointment_id', models.CharField(blank=True, db_column='appointmentId', max_length=191, null=True)),
                ('doctor_id', models.CharField(blank=True, db_column='doctorId', max_length=191, null=True)),
                ('service_id', models.CharField(blank=True, db_column='serviceId', max_length=191, null=True)),
                ('shown_queue_number', models.IntegerField(blank=True, db_column='shownQueueNumber', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'DisplayState',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('name_fr', models.CharField(db_column='nameFr', max_length=191)),
                ('name_ar', models.CharField(db_column='nameAr', max_length=191)),
                ('title_fr', models.CharField(db_column='titleFr', max_length=191)),
                ('title_ar', models.CharField(db_column='titleAr', max_length=191)),
                ('photo_url', models.TextField(blank=True, db_column='photoUrl', null=True)),
                ('active', models.BooleanField(default=True)),
                ('schedule_json', models.JSONField(db_column='scheduleJson')),
                ('morning_capacity', models.IntegerField(db_column='morningCapacity', default=0)),
                ('evening_capacity', models.IntegerField(db_column='eveningCapacity', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'Doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorQueueCounter',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField(db_column='appointmentDate')),
                ('slot', models.CharField(choices=[('MORNING', 'MORNING'), ('EVENING', 'EVENING')], max_length=20)),
                ('last_number', models.IntegerField(db_column='lastNumber', default=0)),
            ],
            options={
                'db_table': 'DoctorQueueCounter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('name_fr', models.CharField(db_column='nameFr', max_length=191)),
                ('name_ar', models.CharField(db_column='nameAr', max_length=191)),
                ('description_fr', models.TextField(db_column='descriptionFr')),
                ('description_ar', models.TextField(db_column='descriptionAr')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'Service',
                'managed': False,
            },
        ),
    ]
